title: Stackbit Fjord Theme
baseURL: /
params:
  footer:
    content: '&copy; Prepare Zone LLC. All rights reserved.'
    links:
      - new_window: true
        text: prepare.zone
        url: 'https://prepare.zone'
  header:
    bg_img: /images/header-bg.jpg
    has_nav: true
    has_social: true
    logo_img: /images/logopz_l.png
    tagline: Minimal and clean blog theme
    title: Project Design & CRM
  palette: yellow
disableKinds:
  - RSS
